source "AEpaintingUtilFuncs";
source "AEpaintingBrushes";
source "AEsortFilterInclude";

global proc AEbrushLifterTemplate ( string $nodeName )
{
	editorTemplate -beginScrollLayout;

	editorTemplate -cl 0 -beginLayout "Brushes";
 	editorTemplate -callCustom "AEpaintingBrushesNew" "AEpaintingBrushesReplace" "brushes";
 	editorTemplate -endLayout;

 	AEsortFilterInclude($nodeName);
 
	editorTemplate -addExtraControls;
	editorTemplate -endScrollLayout;
	
}
