global proc AEgateRampTemplate ( string $nodeName )
{

	editorTemplate -beginScrollLayout;


	editorTemplate -cl 0  -beginLayout "General attributes";		
	editorTemplate -addControl "numGates" ;
	editorTemplate -addControl "range" ;
	editorTemplate -addControl "padding" ;
	AEaddRampControl("ramp");		
	editorTemplate -endLayout;
	editorTemplate -addExtraControls;
	editorTemplate -endScrollLayout;
	
}

