---
configuration: debug
product_name: uprising
product_description: Robot painting tools.
configuration_debug:
  product_revision: 2017.dev.999
configuration_release:
  product_revision: 1.16.0
author_name: Julian Mann
author_email: julian.mann@gmail.com
os_darwin64:
  platform_id: darwin64
  configuration_debug:
    tools_directory: ${MY_TOOLS}
  configuration_release:
    tools_directory: ${MY_TOOLS}
os_linux64:
  platform_id: ${PLATFORM_ID}
  configuration_debug:
    tools_directory: ${MY_TOOLS}
  configuration_release:
    tools_directory: ${FLAK_RELEASE_TOOLS}
os_win64:
  platform_id: win64
  configuration_debug:
    tools_directory: /cygdrive/c/cygwin/${MY_TOOLS}
  configuration_release:
    tools_directory: ${MY_TOOLS}
