os_linux64:
    libs:
    - 'OpenMayalib'
    - 'dl'
    maya_relative_lib_path: 'lib'
    maya_relative_inc_path: 'include'
    linker_options: 
    - '-m64'
    - '-pthread'
    compiler_options:
    - '-g'
    - '-fno-gnu-keywords' 
    - '-ftemplate-depth-25'
    - '-Wno-multichar' 
    - '-Wno-comment'   
    - '-Wno-reorder'    	  
    - '-Wno-sign-compare' 
    - '-Wall' 
    libs:
    - 'OpenMaya'
    - 'AnimSlice'
    - 'DeformSlice'
    - 'Modifiers'
    - 'DynSlice'
    - 'KinSlice'
    - 'ModelSlice'
    - 'NurbsSlice'
    - 'PolySlice '
    - 'ProjectSlice'
    - 'Image'
    - 'Shared'
    - 'Translators'
    - 'DataModel'
    - 'RenderModel'
    - 'NurbsEngine'
    - 'DependEngine'
    - 'CommandEngine'
    - 'Foundation'
    - 'IMFbase'
    - 'm'
os_darwin64:
    maya_relative_lib_path: 'Maya.app/Contents/MacOS'
    maya_relative_inc_path: 'devkit/include'
    compiler_options:
    - '-fno-gnu-keywords' 
    - '-fpascal-strings'
    libs:
    - 'OpenMaya'
    - 'AnimSlice'
    - 'DeformSlice'
    - 'Modifiers'
    - 'DynSlice'
    - 'KinSlice'
    - 'ModelSlice'
    - 'NurbsSlice'
    - 'PolySlice '
    - 'ProjectSlice'
    - 'Image'
    - 'Shared'
    - 'Translators'
    - 'DataModel'
    - 'RenderModel'
    - 'NurbsEngine'
    - 'DependEngine'
    - 'CommandEngine'
    - 'Foundation'
    - 'IMFbase'
    - 'm'
os_win64:
    libs:
    - 'Foundation'
    - 'OpenMaya'
    maya_relative_inc_path: 'include'
    maya_relative_lib_path: 'lib'
    compiler_options:
    - '/DNT_APP'
    - '/D_CONSOLE'
    - '/D_BOOL'