/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  softwareSidebar: [
    {
      type: "doc",
      id: "software-intro", // document ID
      label: "Introduction" // sidebar label
    },
    { type: "autogenerated", dirName: "software" }
  ],
  hardwareSidebar: [
    {
      type: "doc",
      id: "hardware-intro", // document ID
      label: "Introduction" // sidebar label
    },
    { type: "autogenerated", dirName: "hardware" }
  ],
    resourcesSidebar: [
      {
        type: "doc",
        id: "resources-intro", // document ID
        label: "Introduction" // sidebar label
      },
      { type: "autogenerated", dirName: "resources" }
  ]

};

module.exports = sidebars;
